no_cuda: False
dataset: "mnist"
ensemble_learning: "bagging"
download_data: True
ensemble:
      - model:
              count: 5
              pretrained: null
              bin_type: "xnor"
              model_type: "nin"
              train_batch_size: 128
              test_batch_size: 100
              optimizer: "adam"
              lr: 0.01
              gamma: 0.1
              steps: [80, 150]
              epochs: 100
              checkpoint: "results/xnor_lenet5"
              train_labels:
                    - [0, 1, 2, 3]
                    - [2, 3, 4, 5]
                    - [4, 5, 6, 7]
                    - [6, 7, 8, 9]
                    - [8, 9, 0, 1]
