no_cuda: False
dataset: "mnist"
ensemble_learning: "dynamic_expert_vote"
download_data: True
ensemble:
      - model:
              count: 1
              pretrained: null
              bin_type: "xnor"
              model_type: "lenet5"
              train_batch_size: 128
              test_batch_size: 100
              optimizer: "adam"
              lr: 0.01
              gamma: 0.1
              steps: [80, 150]
              epochs: 100
              checkpoint: "results/xnor_lenet5"
              train_labels:
                    - all
      - model:
              count: 4
              pretrained: null
              bin_type: "xnor"
              model_type: "lenet_expert"
              train_batch_size: 128
              test_batch_size: 100
              optimizer: "adam"
              lr: 0.01
              gamma: 0.1
              steps: [80, 150]
              epochs: 100
              checkpoint: "results/xnor_expert_lenet"
              train_labels:
                    - [4, 9, 7, 1]
                    - [5, 8, 3, 2]
                    - [0, 6, 5, 3]
                    - [1, 2, 8, 7]
