no_cuda: False
dataset: "cifar10"
ensemble_learning: "bagging"
ensemble:
    - model:
          count: 1
          pretrained: null
          bin_type: "xnor"
          model_type: "lenet5"
          train_batch_size: 128
          test_batch_size: 100
          optimizer: "adam"
          lr: 0.01
          gamma: 0.1
          steps: [80, 150]
          epochs: 100
          checkpoint: "results/lenet_cifar10/xnor_lenet5"
          train_labels:
              - all
    - model:
          count: 6
          pretrained: null
          bin_type: "xnor"
          model_type: "lenet_expert"
          train_batch_size: 128
          test_batch_size: 100
          optimizer: "adam"
          lr: 0.01
          gamma: 0.1
          steps: [80, 150]
          epochs: 100
          checkpoint: "results/lenet_cifar10/xnor_expert"
          train_labels:
              - [1, 0, 9, 8]
              - [8, 0, 5, 2]
              - [2, 5, 4, 6]
              - [6, 4, 2, 3, 5]
              - [7, 2, 4, 3]
              - [7, 0, 3, 8]
