no_cuda: False
checkpoint: "results/nin_cifar10"
save_path: "results/nin_cifar10"
dataset: "cifar10"
ensemble_learning: "bagging"
download_data: True
ensemble:
    - model:
          count: 1
          pretrained: null
          bin_type: "xnor"
          model_type: "nin"
          batch_size: 128
          test_batch_size: 100
          optimizer: "adam"
          lr: 0.01
          gamma: 0.1
          steps: [80, 150]
          epochs: 100
          train_labels:
              - all
    - model:
          count: 6
          pretrained: null
          bin_type: "xnor"
          model_type: "nin"
          batch_size: 128
          test_batch_size: 100
          optimizer: "adam"
          lr: 0.01
          gamma: 0.1
          steps: [80, 150]
          epochs: 100
          train_labels:
              - [0, 1, 8, 9]
              - [8, 0, 5, 2]
              - [2, 5, 4, 6]
              - [6, 4, 2, 3, 5]
              - [7, 2, 4, 3]
              - [1, 2, 4, 5]
