no_cuda: False
classifier:
  checkpoint: "results/nin_cifar10"
  save_path: "results/nin_cifar10"
  dataset: "cifar10"
  ensemble_learning: "bagging"
  ensemble:
    - model:
        count: 1
        pretrained: null
        bin_type: "xnor"
        model_type: "nin"
        batch_size: 128
        test_batch_size: 100
        optimizer: "adam"
        lr: 0.01
        gamma: 0.1
        steps: [80, 150]
        epochs: 100
    - model:
        count: 3
        pretrained: null
        bin_type: "xnor"
        model_type: "nin"
        batch_size: 128
        test_batch_size: 100
        optimizer: "adam"
        lr: 0.01
        gamma: 0.1
        steps: [80, 150]
        epochs: 100
